spring.application.name=online-bank
#DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/atm_db
spring.datasource.username=atm_user
spring.datasource.password=atm123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

jwt.secret=mySecretKeyForJWTTokenGenerationOnlineBankApp2026
jwt.expiration=86400000
