spring.application.name=online-bank
#DB connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/atm_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:atm_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:atm1234}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

jwt.secret=${JWT_SECRET:mySecretKeyForJWTTokenGenerationOnlineBankApp2026}
jwt.expiration=${JWT_EXPIRATION:86400000}
